# Generated by Django 4.1.3 on 2022-11-22 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(blank=True, db_column='firstName', null=True)),
                ('lastname', models.TextField(blank=True, db_column='lastName', null=True)),
                ('birthdate', models.DateTimeField(blank=True, db_column='birthDate', null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('audiobook', models.TextField(blank=True, db_column='audioBook', null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imdb', models.TextField(blank=True, null=True)),
                ('youtube', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'preferences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookUsers',
            fields=[
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('userid', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recommendation_service_api.users')),
            ],
            options={
                'db_table': 'book_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreferenceUsers',
            fields=[
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('userid', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recommendation_service_api.users')),
            ],
            options={
                'db_table': 'preference_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserBooks',
            fields=[
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('bookid', models.OneToOneField(db_column='bookId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recommendation_service_api.books')),
            ],
            options={
                'db_table': 'user_books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('preferenceid', models.OneToOneField(db_column='preferenceId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recommendation_service_api.preferences')),
            ],
            options={
                'db_table': 'user_preference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('bookid', models.ForeignKey(db_column='bookId', on_delete=django.db.models.deletion.DO_NOTHING, to='recommendation_service_api.books')),
            ],
        ),
    ]
