# Generated by Django 4.1.3 on 2022-12-13 20:02

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_service_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', jsonfield.fields.JSONField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation_service_api.user')),
            ],
            options={
                'verbose_name': 'UserRecommendation',
                'verbose_name_plural': 'UserRecommendations',
            },
        ),
    ]
