# Generated by Django 4.1.3 on 2022-12-04 15:29

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_service_api', '0003_rename_books_recommendations_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendations',
            name='rating',
        ),
        migrations.AddField(
            model_name='recommendations',
            name='recommendations',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
